# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!



pod 'VinliNet', :path => '~/Documents/Programs/Vinli/ios-net'
pod 'Mapbox-iOS-SDK' , '~> 3.2.1'

target 'Commute' do

end

target 'CommuteTests' do

end

target 'CommuteUITests' do

end

