# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ios-net-demo' do
pod ‘VinliNet’
end

target 'ios-net-demoTests' do

end

target 'ios-net-demoUITests' do

end

